name: "Release & Bundle"

on:
  push:
    tags:
      - "v_*"

jobs:
  build-and-release:
    name: "Bundeln und Veröffentlichen"
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      #  Node.js, um den Bundler auszuführen
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # esbuild installieren
      - name: Install esbuild
        run: npm install -g esbuild

      # BUNDLING
      - name: Bundle Javascript
        run: |
          esbuild dist/bms-battery-cells-card.js --bundle --minify --format=esm --outfile=bms-battery-cells-card.js

      # Release erstellen und die EINE Datei hochladen
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          files: bms-battery-cells-card.js
